# action.yml
name: 'update tag'
description: 'Greet someone and record the time'
inputs:
  latest-tag:  # id of input
    description: 'latest tag version'
    required: true
    type: string
    default: ''
  message:
    description: 'commit message'
    required: true
    type: string
    default: ''
outputs:
  tag: # id of output
    description: 'new tag'
    value: ${{ steps.updater.outputs.tag }}
runs:
  using: 'composite'
  steps: 
    - name: script
      id: update
      shell: bash
      run: |
        if [[ "$LATEST_TAG" =~ ^v(.*) ]]; then 
            NUM=${BASH_REMATCH[1]}; 
        else 
            NUM=$LATEST_TAG
        fi
        if [[ "$MESSAGE" =~ '[major]' ]]; then
            NEW_TAG=$(echo $NUM | awk -F. -v OFS=. '{$1 += 1 ; $2 = 0; $3 = 0; print}')
        elif [[ "$MESSAGE" =~ '[minor]' ]]; then
            NEW_TAG=$(echo $NUM | awk -F. -v OFS=. '{$2 += 1 ; $3 = 0; print}')
        else
          NEW_TAG=$(echo $NUM | awk -F. -v OFS=. '{$3 += 1 ; print}')
        fi
        echo "NEWTAG=v1.0.2" >> $GITHUB_ENV
      env:
        LATEST_TAG: ${{ inputs.latest-tag }}
        MESSAGE: ${{ inputs.message }}