# action.yml
name: 'update tag'
description: 'Greet someone and record the time'
inputs:
  path:  # id of input
    description: 'the path to zip up recursively'
    required: true
    type: string
    default: '.'
  zip-flle-name:
    description: 'name of zip file'
    required: true
    type: string
    default: 'files.zip'
  exclusions:
    description: 'files to exclude, space seprated'
    required: false
    type: string
    default: ''
  inclusions:
    description: 'files to include, space separated'
    required: false
    type: string
    default: ''
runs:
  using: 'composite'
  steps: 
    - name: script
      id: update
      shell: bash
      run: |
        CMD="/usr/bin/zip -r $ZIPFILENAME $PATH "
        if [[ $INCLUDES != '' ]]; then
          CMD="${CMD} -i ${INCLUDES} "
        fi
        if [[ $EXCLUDES != '' ]]; then
          CMD="${CMD} -x ${EXCLUDES} "
        fi
        $CMD
      env:
        PATH: ${{ inputs.path }}
        ZIPFILENAME: ${{ inputs.zip-file-name }}
        INCLUDES: ${{ inputs.includes }}
        EXCLUDES: ${{ inputs.excludes }}
